---
linters:
  FinalNewline:
    enabled: true
  SelfClosingTag:
    enabled: false
  SpaceAroundErbTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
  Rubocop:
    enabled: true
    only:
      - Layout/EndOfLine
      - Lint/LiteralAsCondition
      - Style/PercentLiteralDelimiters
