env:
  browser: true
  es6: false
extends: "eslint:recommended"
globals:
  $: readonly
  App: readonly
  annotator: readonly
  c3: readonly
  CKEDITOR: readonly
  L: readonly
  Turbolinks: readonly
parserOptions:
  ecmaVersion: 5
rules:
  array-bracket-spacing: error
  block-spacing: error
  brace-style: error
  comma-spacing: error
  computed-property-spacing: error
  curly: error
  eol-last: error
  func-call-spacing: error
  indent:
    - error
    - 2
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  lines-between-class-members: error
  no-console: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-spaced-func: error
  no-tabs: error
  no-trailing-spaces: error
  no-void: error
  no-whitespace-before-property: error
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  padded-blocks:
    - error
    - never
  quotes:
    - error
    - double
    - avoidEscape: true
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
    - markers:
        - "="
      exceptions:
        - "-"
  strict: error
  switch-colon-spacing: error
