rubocop:
  config_file: .rubocop_basic.yml
  version: 0.72.0
scss:
  config_file: .scss-lint.yml
erblint:
  enabled: true
  config_file: .erb-lint.yml
eslint:
  enabled: true
  config_file: .eslintrc.yml
