inherit_from: .rubocop_basic.yml

Performance/CompareWithBlock:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/StartWith:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
