inherit_from: .rubocop_basic.yml

Bundler/InsecureProtocolSource:
  Enabled: true

Performance/CompareWithBlock:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/StartWith:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/EnvironmentComparison:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEql:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribeMethod:
  Enabled: true

RSpec/DescribeSymbol:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectInHook:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/FilePath:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: should

RSpec/InstanceSpy:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/InvalidPredicateMatcher:
  Enabled: true

RSpec/ItBehavesLike:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/MessageChain:
  Enabled: true

RSpec/MessageExpectation:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MultipleDescribes:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/PredicateMatcher:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/ReturnFromStub:
  Enabled: true

RSpec/SharedContext:
  Enabled: true

RSpec/SingleArgumentMessageChain:
  Enabled: true

RSpec/SubjectStub:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
