require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"
  TargetRubyVersion: 2.3
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true

Capybara/FeatureMethods:
  Enabled: true
  EnabledMethods:
    - scenario
    - xscenario

FactoryBot/AttributeDefinedStatically:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentationWidth:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/LineLength:
  Max: 110

Rails/ActionFilter:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

RSpec/NotToNot:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
